services:
  huduma-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: huduma-client
    ports:
      - '5173:5173'
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - huduma-voice-server
      - huduma-voice-bot
    container_name: "huduma-frontend"
    env_file:
      - '/client/.env'
  huduma-voice-bot:
    build:
      context: ./huduma-bot
      dockerfile: Dockerfile
    image: huduma-voice-bot
    ports:
      - '5000:5000'
    volumes:
      - ./huduma-bot:/app
      - /app/node_modules
    env_file:
      - '/huduma-bot/.env'
    container_name: "huduma-bot"
  huduma-voice-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: huduma-voice-server
    ports:
      - '8000:8000'
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - '/server/.env'
    container_name: "huduma-server"